[2023-09-16T04:16:42.940+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: branching_example.branching manual__2023-09-16T04:16:41.838391+00:00 [queued]>
[2023-09-16T04:16:42.946+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: branching_example.branching manual__2023-09-16T04:16:41.838391+00:00 [queued]>
[2023-09-16T04:16:42.947+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-16T04:16:42.958+0000] {taskinstance.py:1380} INFO - Executing <Task(BranchPythonOperator): branching> on 2023-09-16 04:16:41.838391+00:00
[2023-09-16T04:16:42.961+0000] {standard_task_runner.py:57} INFO - Started process 1288 to run task
[2023-09-16T04:16:42.963+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'branching_example', 'branching', 'manual__2023-09-16T04:16:41.838391+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/task.py', '--cfg-path', '/tmp/tmpkhl5icyh']
[2023-09-16T04:16:42.964+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask branching
[2023-09-16T04:16:42.995+0000] {task_command.py:415} INFO - Running <TaskInstance: branching_example.branching manual__2023-09-16T04:16:41.838391+00:00 [running]> on host 63e9c8165189
[2023-09-16T04:16:43.048+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='branching_example' AIRFLOW_CTX_TASK_ID='branching' AIRFLOW_CTX_EXECUTION_DATE='2023-09-16T04:16:41.838391+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-16T04:16:41.838391+00:00'
[2023-09-16T04:16:43.049+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 226, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: separate_even_and_odd() missing 1 required positional argument: 'numbers'
[2023-09-16T04:16:43.053+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=branching_example, task_id=branching, execution_date=20230916T041641, start_date=20230916T041642, end_date=20230916T041643
[2023-09-16T04:16:43.064+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task branching (separate_even_and_odd() missing 1 required positional argument: 'numbers'; 1288)
[2023-09-16T04:16:43.096+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-16T04:16:43.115+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
